### GET request to example server
GET http://127.0.0.1:8000/
###

### GET request to example server
GET http://127.0.0.1:8000/student/
###


###
POST 127.0.0.1:8000/student/
Content-Type: application/json

{
 "name": "testing nine",
 "age": 26,
 "father_name": "Vinod"
}
###

###
PATCH 127.0.0.1:8000/student/
Content-Type: application/json

{
  "id" : 3,
  "name": "xyz_updated_updated",
  "age": 29
}
###

###
DELETE 127.0.0.1:8000/student/
Content-Type: application/json

{
  "id": "3"
}
###

###
GET 127.0.0.1:8000/get_book/
###


#token: b18b219eb5d44f4bdf0607b0655308a6f15a072a
###
POST 127.0.0.1:8000/api-token-auth/
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}
###

###
POST 127.0.0.1:8000/register/
Content-Type: application/json

{
  "username": "testing",
  "password": "123"
}
###